
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo3d.backend.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 3;
  public static final int HIGHER_EQ = 38;
  public static final int NUM_INTEGER = 44;
  public static final int ELSIF = 17;
  public static final int NOT_EQUAL = 41;
  public static final int LOWER = 39;
  public static final int DOUBLE = 8;
  public static final int INT = 5;
  public static final int PRINTLN = 23;
  public static final int ARRAY = 15;
  public static final int FOR = 21;
  public static final int MINUS = 33;
  public static final int NOT = 10;
  public static final int SEMICOLON = 30;
  public static final int AND = 11;
  public static final int OR = 12;
  public static final int COMMA = 24;
  public static final int SEPARATOR = 52;
  public static final int PLUS = 32;
  public static final int MAIN = 50;
  public static final int ASSIGN = 31;
  public static final int IF = 16;
  public static final int LOWER_EQ = 37;
  public static final int OPEN_BRK = 26;
  public static final int CLOSE_BRK = 27;
  public static final int EOF = 0;
  public static final int BOOLEAN = 2;
  public static final int RETURN = 51;
  public static final int EQUAL = 42;
  public static final int TRUE = 13;
  public static final int error = 1;
  public static final int HIGHER = 40;
  public static final int BYTE = 4;
  public static final int MODULE = 36;
  public static final int COLON = 25;
  public static final int ELSE = 18;
  public static final int VARIABLE = 47;
  public static final int OPEN_SQR = 28;
  public static final int CLOSE_SQR = 29;
  public static final int WHILE = 19;
  public static final int FLOAT = 7;
  public static final int MULTI = 34;
  public static final int LONG = 6;
  public static final int STRING = 9;
  public static final int NUM_DOUBLE = 45;
  public static final int TEXT = 43;
  public static final int NUM_FLOAT = 46;
  public static final int FALSE = 14;
  public static final int DIVISION = 35;
  public static final int SCANS = 48;
  public static final int PRINT = 22;
  public static final int DO = 20;
  public static final int SCANN = 49;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOLEAN",
  "CHAR",
  "BYTE",
  "INT",
  "LONG",
  "FLOAT",
  "DOUBLE",
  "STRING",
  "NOT",
  "AND",
  "OR",
  "TRUE",
  "FALSE",
  "ARRAY",
  "IF",
  "ELSIF",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "PRINT",
  "PRINTLN",
  "COMMA",
  "COLON",
  "OPEN_BRK",
  "CLOSE_BRK",
  "OPEN_SQR",
  "CLOSE_SQR",
  "SEMICOLON",
  "ASSIGN",
  "PLUS",
  "MINUS",
  "MULTI",
  "DIVISION",
  "MODULE",
  "LOWER_EQ",
  "HIGHER_EQ",
  "LOWER",
  "HIGHER",
  "NOT_EQUAL",
  "EQUAL",
  "TEXT",
  "NUM_INTEGER",
  "NUM_DOUBLE",
  "NUM_FLOAT",
  "VARIABLE",
  "SCANS",
  "SCANN",
  "MAIN",
  "RETURN",
  "SEPARATOR"
  };
}

